### ISSUE TITLE
바닥에 플레이어가 완전히 붙지 않음.

### ISSUE THREAD

**Issue by hktrollgames** [kksumm123/JumpJump#1]
원인 : 2D 물리 충돌시 조금의 간격을 띄우고 있음.

해결책 1: 3D물리로 바꾼다(리지드 바디와 충돌체 모두)

해결책 2 : 플레이어의 보이는 크기를 늘리거나(더큰 스프라이트 사용) 혹은 플레이어의 콜라이더 크기를 이미지 크기보다 줄인다

완벽한 해결책 : [찾지 못함] 2D물리에서 물리 충돌이 정밀히 계산되도록 하는 수치 조절 같은건 찾지 못했다. 
2D 물리 충돌시 조금의 간격을 띄우고 있는 이유도 찾지 못했다

[참고] 2D물리와 3D물리는 다른 물리 엔진을 사용함

**Comment by hktrollgames** [comment]
완벽한 해결책 찾음
https://answers.unity.com/questions/774350/unrealistic-gap-between-two-objects.html

Project Setting -> Physics 2D -> Default Contact Offset 을 최소값(0.0001)으로 수정하면 됨 
![image](https://user-images.githubusercontent.com/82859113/121913559-77806f80-cd6c-11eb-9b2e-5b4143bdc988.png)

**Comment by kksumm123** [comment]
감사합니다 !
